[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending_protocol = "5jCuVD2zuLBFyt5PsVEXMaAdMCtj4vM9zML1s3ZSQx7v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
[[test.genesis]]
address = "Bv3Fb9VjzjWGfX18QTUcVycAfeLoQ5zZN6vv2g3cTZxp"
program = "/mnt/c/Users/HP/web3-projects/lending_protocol/smart contract/artifacts/arcium_program_0.4.0.so"
























[test]
startup_wait = 200000 

[[test.validator.account]]
address = "AxygBawEvVwZPetj3yPJb9sGdZvaJYsVguET1zFUQkV"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "FsWbPQcJQ2cCyr9ndse13fDqds4F2Ezx2WgTL25Dke4M"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "Dhu3UEtRGE5iKzXJUiiFStJL4F63eW4nJMRd3dAg9WJK"
filename = "artifacts/wallet_acc_Dhu3_9WJK.json"

[[test.validator.account]]
address = "Fdw8LypaUTMW98C4kBw7PUErehRZkWGbTqv2sWtbw6nJ"
filename = "artifacts/arx_ata_Dhu3_9WJK.json"

[[test.validator.account]]
address = "GjDAT4Af81MuWjZUmYzboc8Zqii6aTbsKHT5A2VrsFZx"
filename = "artifacts/wallet_acc_GjDA_sFZx.json"

[[test.validator.account]]
address = "5M3c42LWfeLhNuVNeZyMUHAr39xDctkecuVBLpPhv8LN"
filename = "artifacts/wallet_acc_callback_5M3c_v8LN.json"

[[test.validator.account]]
address = "3K3zvxrNDZkLoMVv8BmgAmiNDk66yfxon2aykPwrdE7V"
filename = "artifacts/arx_ata_GjDA_sFZx.json"

[[test.validator.account]]
address = "6WXF4kP3DjkxNKiozNBKiJzPfkqJMNLsNkBRvgAs7nhp"
filename = "artifacts/operator_acc_GjDA_sFZx.json"

[[test.validator.account]]
address = "5ukYx6pm48uSuquhgKonbnEEfdduXNGHfkpRYGjMo38L"
filename = "artifacts/arx_node_GjDA_sFZx.json"

[[test.validator.account]]
address = "8mN217vHf8XNtS3qGVKeqdnheP3nhRqKtLfJiJbgcsKn"
filename = "artifacts/wallet_acc_8mN2_csKn.json"

[[test.validator.account]]
address = "BB9F5skVRjKhSyMjqpFJhU1nwnHE6SHpDN4MsDezf55q"
filename = "artifacts/wallet_acc_callback_BB9F_f55q.json"

[[test.validator.account]]
address = "72fmRzZQLSWEdm7hsBwyiuJBtYR4r1kQjBv7T4WmbUDk"
filename = "artifacts/arx_ata_8mN2_csKn.json"

[[test.validator.account]]
address = "5kNN1Cj5Jn3M3Zmqtni1xuD2jkrRFkWwpJPiL3cfCcRR"
filename = "artifacts/operator_acc_8mN2_csKn.json"

[[test.validator.account]]
address = "8FkwbkcVhmmJrYhpNGZvvhkJ464xMsxeq8zx851CGN99"
filename = "artifacts/arx_node_8mN2_csKn.json"

[[test.validator.account]]
address = "2E4qQsaFWEWFbyKRDEaK2bAWQLFnk9MDRv6PCpViArmN"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "CbVcAZesTjtxrJzhimPUxXZAKt6ZYeUkUw8QppryRELJ"
filename = "artifacts/check_health_factor_raw_circuit_0.json"

[[test.validator.account]]
address = "EZJkZpdJKso4bHzLb3wUc7EYqpJSNMs2rVwVoRAaW1vy"
filename = "artifacts/check_liquidation_raw_circuit_0.json"

[[test.validator.account]]
address = "39bA1jSKZeAtc6RMoL7HtYJSyzQ3GFMRVCJGSR53gpb8"
filename = "artifacts/mxe_keygen_comp_def.json"

[[test.validator.account]]
address = "EmQWkjc2kBDjJhUjaMPdn2Z4PSPuyU3VjTLfw6MdXomU"
filename = "artifacts/mxe_keygen_comp.json"

[[test.validator.account]]
address = "AC2MDVrtcGaM8MGaFb8VA1R6UFxP4iN9bboaHufsAWDF"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "Gaf53fGFMSpUKf5vZ9pnk7DA56JAwMPti2gnssYDd2UJ"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "2u24TnfZwu5RXBR3kSwFrpAEPzox48CpzZFHPeibz9YK"
filename = "artifacts/executing_pool_acc.json"
